name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    env:
      TF_VAR_vercel_api_token: ${{ secrets.VERCEL_API_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.4
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform -chdir=terraform init -input=false

    - name: Terraform Plan
      run: terraform -chdir=terraform plan -input=false

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve -input=false